from datetime import datetime
from html import unescape
import re
from typing import Any

from pydantic import Field

from src.modules.email_template.domain.enums.template_enums import (
    TemplateAssetTypeEnum,
    TemplateAssetUsageEnum,
    TemplateStatusEnum,
)
from src.shared.schemas import (
    BaseSchema,
    DomainEmail,
    DomainString,
    NameString,
    field_validator,
)


def _clean_optional_text(
    value: Any,
) -> Any:
    """
    Trims optional text and converts blank strings to None.
    """
    if isinstance(value, str):
        value = value.strip()
        return value or None

    return value


def _clean_tags(
    value: Any,
) -> list[str]:
    """
    Trims, validates, and removes duplicate template tags.
    """
    if value is None:
        return []

    if not isinstance(value, list):
        raise ValueError(
            "Template tags must be provided as a list"
        )

    cleaned_tags: list[str] = []
    seen_tags: set[str] = set()

    for tag in value:
        if not isinstance(tag, str):
            raise ValueError(
                "Each template tag must be a string"
            )

        cleaned_tag = tag.strip()

        if not cleaned_tag:
            continue

        if len(cleaned_tag) > 50:
            raise ValueError(
                "Each template tag cannot exceed 50 characters"
            )

        normalized_tag = cleaned_tag.casefold()

        if normalized_tag in seen_tags:
            continue

        seen_tags.add(normalized_tag)
        cleaned_tags.append(cleaned_tag)

    if len(cleaned_tags) > 20:
        raise ValueError(
            "A template cannot contain more than 20 tags"
        )

    return cleaned_tags


def _validate_sender_name(
    value: Any,
) -> Any:
    """Validates the optional sender display name."""
    value = _clean_optional_text(value)
    if value is None:
        return None
    if len(value) > 50:
        raise ValueError("From Name cannot exceed 50 characters")
    if not any(character.isalpha() for character in value):
        raise ValueError("From Name must contain at least one letter")
    return value


def _validate_sender_email_length(
    value: Any,
) -> Any:
    """Keeps the short sender-email field within the product limit."""
    value = _clean_optional_text(value)
    if value is not None and len(value) > 50:
        raise ValueError("From Email cannot exceed 50 characters")
    return value


def _validate_body_html(
    value: Any,
) -> Any:
    """
    Prevents an empty template body.

    The original HTML is returned because spacing and formatting may be
    generated by the frontend rich-text editor.
    """
    if not isinstance(value, str) or not value.strip():
        raise ValueError("Email body cannot be empty")

    if len(value) > 200_000:
        raise ValueError("Email body is too large")

    without_script = re.sub(r"<(script|style)\b[^>]*>.*?</\1>", " ", value, flags=re.I | re.S)
    visible_text = re.sub(r"<[^>]+>", " ", without_script)
    visible_text = unescape(visible_text).replace("\xa0", " ").strip()
    has_image = bool(re.search(r"<img\b[^>]*\bsrc\s*=\s*['\"][^'\"]+['\"]", value, flags=re.I))
    if not visible_text and not has_image:
        raise ValueError("Email body cannot be empty")

    return value


class CreateTemplateRequestSchema(BaseSchema):
    """
    Request schema for creating a custom template.

    The frontend rich-text editor generates body_html automatically.
    The user writes and formats the content normally.
    """

    name: NameString = Field(min_length=1, max_length=50)
    subject: str = Field(min_length=1, max_length=255)
    body_html: str = Field(min_length=1, max_length=200_000)

    description: str | None = Field(default=None, max_length=500)
    preheader: str | None = Field(default=None, max_length=255)
    from_name: str | None = Field(default=None, max_length=50)
    from_email: DomainEmail | None = Field(default=None, max_length=50)

    category_id: int | None = Field(default=None, ge=1)

    tags: list[str] = Field(
        default_factory=list,
    )

    is_default: bool = False
    smart_personalization_enabled: bool = False

    @field_validator("name", mode="before")
    @classmethod
    def clean_name(cls, value: Any) -> Any:
        if isinstance(value, str):
            value = value.strip()
        if not value:
            raise ValueError("Template name is required")
        return value

    @field_validator("subject", mode="before")
    @classmethod
    def clean_subject(cls, value: Any) -> Any:
        if isinstance(value, str):
            value = value.strip()
        if not value:
            raise ValueError("Subject line is required")
        return value

    @field_validator(
        "description",
        "preheader",
        "from_name",
        mode="before",
    )
    @classmethod
    def clean_optional_text(
        cls,
        value: Any,
    ) -> Any:
        """
        Trims optional template text fields.
        """
        return _clean_optional_text(value)

    @field_validator(
        "from_name",
        mode="before",
    )
    @classmethod
    def validate_sender_name(
        cls,
        value: Any,
    ) -> Any:
        return _validate_sender_name(value)

    @field_validator(
        "from_email",
        mode="before",
    )
    @classmethod
    def validate_sender_email_length(
        cls,
        value: Any,
    ) -> Any:
        return _validate_sender_email_length(value)

    @field_validator(
        "tags",
        mode="before",
    )
    @classmethod
    def clean_tags(
        cls,
        value: Any,
    ) -> list[str]:
        """
        Cleans and validates template tags.
        """
        return _clean_tags(value)

    @field_validator(
        "body_html",
        mode="before",
    )
    @classmethod
    def validate_body_html(
        cls,
        value: Any,
    ) -> Any:
        """
        Prevents creating a template with an empty body.
        """
        return _validate_body_html(value)


class UpdateTemplateRequestSchema(BaseSchema):
    """
    Request schema for editing a custom template.

    Only fields included in the request are updated.
    """

    name: NameString | None = Field(default=None, max_length=50)
    subject: str | None = Field(default=None, max_length=255)
    body_html: str | None = Field(default=None, max_length=200_000)

    description: str | None = Field(default=None, max_length=500)
    preheader: str | None = Field(default=None, max_length=255)
    from_name: str | None = Field(default=None, max_length=50)
    from_email: DomainEmail | None = Field(default=None, max_length=50)

    category_id: int | None = Field(default=None, ge=1)
    tags: list[str] | None = None

    is_default: bool | None = None
    smart_personalization_enabled: bool | None = None

    @field_validator("name", mode="before")
    @classmethod
    def clean_name(cls, value: Any) -> Any:
        if value is None:
            return None
        if isinstance(value, str):
            value = value.strip()
        if not value:
            raise ValueError("Template name is required")
        return value

    @field_validator("subject", mode="before")
    @classmethod
    def clean_subject(cls, value: Any) -> Any:
        if value is None:
            return None
        if isinstance(value, str):
            value = value.strip()
        if not value:
            raise ValueError("Subject line is required")
        return value

    @field_validator(
        "description",
        "preheader",
        "from_name",
        mode="before",
    )
    @classmethod
    def clean_optional_text(
        cls,
        value: Any,
    ) -> Any:
        """
        Trims optional editable fields.

        A blank value clears the field.
        """
        return _clean_optional_text(value)

    @field_validator(
        "from_name",
        mode="before",
    )
    @classmethod
    def validate_sender_name(
        cls,
        value: Any,
    ) -> Any:
        return _validate_sender_name(value)

    @field_validator(
        "from_email",
        mode="before",
    )
    @classmethod
    def validate_sender_email_length(
        cls,
        value: Any,
    ) -> Any:
        return _validate_sender_email_length(value)

    @field_validator(
        "tags",
        mode="before",
    )
    @classmethod
    def clean_tags(
        cls,
        value: Any,
    ) -> list[str] | None:
        """
        Cleans tags when they are provided.

        An empty list or explicit null clears existing tags.
        """
        if value is None:
            return []

        return _clean_tags(value)

    @field_validator(
        "body_html",
        mode="before",
    )
    @classmethod
    def validate_body_html(
        cls,
        value: Any,
    ) -> Any:
        """
        Prevents replacing the body with empty content.
        """
        if value is None:
            return None

        return _validate_body_html(value)


class DuplicateTemplateRequestSchema(BaseSchema):
    """
    Optional request schema for duplicating a custom template.
    """

    name: NameString | None = None

    @field_validator(
        "name",
        mode="before",
    )
    @classmethod
    def clean_name(
        cls,
        value: Any,
    ) -> Any:
        """
        Trims the optional duplicate-template name.
        """
        return _clean_optional_text(value)


class TemplateResponseSchema(BaseSchema):
    """
    Summary response for a system or custom template.

    body_html is excluded from normal responses so the API response remains
    clean and readable.
    """

    uuid: str
    organization_id: int | None = None
    category_id: int | None = None
    source_template_id: int | None = None

    name: str
    description: str | None = None
    subject: str
    preheader: str | None = None

    from_name: str | None = None
    from_email: str | None = None

    tags: list[str] = Field(
        default_factory=list,
    )

    template_type: str
    status: str

    is_active: bool
    is_default: bool = False
    smart_personalization_enabled: bool = False

    published_at: datetime | None = None
    archived_at: datetime | None = None

    created_by_id: int | None = None
    updated_by_id: int | None = None

    created_at: datetime | None = None
    updated_at: datetime | None = None

    model_config = {
        "from_attributes": True,
        "extra": "ignore",
    }


class TemplateDetailResponseSchema(
    TemplateResponseSchema
):
    """
    Detailed template response used when opening the template editor.

    The frontend receives body_html and renders it as normal formatted,
    editable content. The user does not see raw HTML tags.
    """

    body_html: str


class TemplateListResponseSchema(BaseSchema):
    """
    Paginated response schema for templates.

    Template list items do not include body_html.
    """

    items: list[TemplateResponseSchema]
    total: int
    limit: int
    offset: int


class TemplateDashboardSummaryResponseSchema(BaseSchema):
    """
    Response schema for template dashboard statistics.
    """

    total_templates: int
    draft_templates: int
    published_templates: int
    archived_templates: int
    total_categories: int

    # This will be populated after the Campaign module exists.
    used_in_campaigns: int | None = None


class PreviewTemplateRequestSchema(BaseSchema):
    """
    Request schema for previewing current editor content.

    The frontend sends the HTML generated by the rich-text editor.
    """

    subject: str
    body_html: str
    preheader: str | None = None
    variables: dict[str, Any] | None = None

    @field_validator(
        "subject",
        mode="before",
    )
    @classmethod
    def clean_subject(
        cls,
        value: Any,
    ) -> Any:
        """
        Trims the preview subject.
        """
        if isinstance(value, str):
            value = value.strip()

        return value

    @field_validator(
        "preheader",
        mode="before",
    )
    @classmethod
    def clean_preheader(
        cls,
        value: Any,
    ) -> Any:
        """
        Trims optional preview text.
        """
        return _clean_optional_text(value)

    @field_validator(
        "body_html",
        mode="before",
    )
    @classmethod
    def validate_body_html(
        cls,
        value: Any,
    ) -> Any:
        """
        Prevents previewing an empty template body.
        """
        return _validate_body_html(value)


class PreviewTemplateResponseSchema(BaseSchema):
    """
    Response schema for rendered template preview.

    body_html is required here because the frontend needs the rendered
    content to display the preview.
    """

    subject: str
    preheader: str | None = None
    body_html: str

    variables: list[str] = Field(
        default_factory=list,
    )

    unresolved_variables: list[str] = Field(
        default_factory=list,
    )

    fallback_variables: list[str] = Field(
        default_factory=list,
    )


class CreateTemplateCategoryRequestSchema(BaseSchema):
    """Request schema for an organization-owned template category."""

    name: str = Field(min_length=1, max_length=50)
    description: str | None = Field(default=None, max_length=500)
    display_order: int = Field(default=0, ge=0, le=10000)


class TemplateCategoryResponseSchema(BaseSchema):
    """
    Response schema for one template category.
    """

    id: int
    uuid: str
    organization_id: int | None = None
    name: str
    description: str | None = None
    display_order: int
    is_active: bool

    model_config = {
        "from_attributes": True,
        "extra": "ignore",
    }


class TemplateCategoryListResponseSchema(BaseSchema):
    """
    Response schema for active template categories.
    """

    items: list[
        TemplateCategoryResponseSchema
    ]


class CreateTemplateAssetRequestSchema(BaseSchema):
    """
    Request schema for uploading a template asset.
    """

    usage: TemplateAssetUsageEnum


class TemplateAssetResponseSchema(BaseSchema):
    """
    Response schema for an inline image or attachment.
    """

    uuid: str
    template_id: int
    organization_id: int | None = None

    original_filename: str
    file_url: str
    content_type: str
    file_size: int

    asset_type: str
    usage: str
    is_active: bool

    uploaded_by_id: int | None = None
    created_at: datetime
    updated_at: datetime | None = None

    model_config = {
        "from_attributes": True,
        "extra": "ignore",
    }


class TemplateAssetListResponseSchema(BaseSchema):
    """
    Paginated response schema for template assets.
    """

    items: list[
        TemplateAssetResponseSchema
    ]

    total: int
    limit: int
    offset: int


class TemplateListQuerySchema(BaseSchema):
    """
    Query schema for listing custom templates.
    """

    status: TemplateStatusEnum | None = None
    category_id: int | None = None
    search: str | None = None

    limit: int = Field(
        default=20,
        ge=1,
        le=100,
    )
    offset: int = Field(
        default=0,
        ge=0,
    )

    @field_validator(
        "search",
        mode="before",
    )
    @classmethod
    def clean_search(
        cls,
        value: Any,
    ) -> Any:
        """
        Trims the template search term.
        """
        return _clean_optional_text(value)


class SystemTemplateListQuerySchema(BaseSchema):
    """
    Query schema for listing system templates.
    """

    category_id: int | None = None
    search: str | None = None

    limit: int = Field(
        default=20,
        ge=1,
        le=100,
    )
    offset: int = Field(
        default=0,
        ge=0,
    )

    @field_validator(
        "search",
        mode="before",
    )
    @classmethod
    def clean_search(
        cls,
        value: Any,
    ) -> Any:
        """
        Trims the system-template search term.
        """
        return _clean_optional_text(value)


class TemplateAssetListQuerySchema(BaseSchema):
    """
    Query schema for listing template assets.
    """

    usage: TemplateAssetUsageEnum | None = None
    asset_type: TemplateAssetTypeEnum | None = None

    limit: int = Field(
        default=50,
        ge=1,
        le=100,
    )
    offset: int = Field(
        default=0,
        ge=0,
    )


class SendTemplateTestEmailRequestSchema(BaseSchema):
    """
    Request schema for sending current editor content as a test email.

    The frontend sends the HTML generated by the rich-text editor.
    """

    email_account_uuid: DomainString
    recipient_email: DomainEmail

    subject: str
    body_html: str

    preheader: str | None = None
    from_name: str | None = None
    variables: dict[str, Any] | None = None

    @field_validator(
        "email_account_uuid",
        "subject",
        mode="before",
    )
    @classmethod
    def clean_required_text(
        cls,
        value: Any,
    ) -> Any:
        """
        Trims required test-email fields.
        """
        if isinstance(value, str):
            value = value.strip()

        return value

    @field_validator(
        "preheader",
        "from_name",
        mode="before",
    )
    @classmethod
    def clean_optional_fields(
        cls,
        value: Any,
    ) -> Any:
        """
        Trims optional test-email fields.
        """
        return _clean_optional_text(value)

    @field_validator(
        "body_html",
        mode="before",
    )
    @classmethod
    def validate_body_html(
        cls,
        value: Any,
    ) -> Any:
        """
        Prevents sending an empty template body.
        """
        return _validate_body_html(value)


class SendTemplateTestEmailResponseSchema(BaseSchema):
    """
    Response schema for a successfully sent test email.

    The email body is not returned.
    """

    recipient_email: str
    sender_email: str
    provider: str
    sent_at: datetime

    provider_message_id: str | None = None
    provider_thread_id: str | None = None

    variables: list[str] = Field(
        default_factory=list,
    )

    unresolved_variables: list[str] = Field(
        default_factory=list,
    )

    fallback_variables: list[str] = Field(
        default_factory=list,
    )
