/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuccessfulLoginRouteImport } from './routes/SuccessfulLogin'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteRouteImport } from './routes/onboarding/route'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SuccessForgotPasswordRouteImport } from './routes/successForgotPassword'
import { Route as Verify2faRouteImport } from './routes/verify-2fa'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as ForgotPasswordIndexRouteImport } from './routes/ForgotPassword/index'
import { Route as ForgotPasswordVerifyRouteImport } from './routes/ForgotPassword/verify'
import { Route as ProtectedCampaignsRouteRouteImport } from './routes/_protected/campaigns/route'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as ProtectedOrganizationRouteRouteImport } from './routes/_protected/organization/route'
import { Route as ProtectedPendingInvitationRouteImport } from './routes/_protected/pending-invitation'
import { Route as ProtectedTemplatesRouteRouteImport } from './routes/_protected/templates/route'
import { Route as InviteIndexRouteImport } from './routes/invite/index'
import { Route as InviteDeclineRouteImport } from './routes/invite/decline'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as OnboardingOnboardingDetailsRouteImport } from './routes/onboarding/onboarding-details'
import { Route as OnboardingThemeSelectionRouteImport } from './routes/onboarding/themeSelection'
import { Route as ProtectedAdminIndexRouteImport } from './routes/_protected/admin/index'
import { Route as ProtectedCampaignsIndexRouteImport } from './routes/_protected/campaigns/index'
import { Route as ProtectedCampaignsCampaignUuidRouteRouteImport } from './routes/_protected/campaigns/$campaignUuid/route'
import { Route as ProtectedCampaignsNewRouteImport } from './routes/_protected/campaigns/new'
import { Route as ProtectedContactsIndexRouteImport } from './routes/_protected/contacts/index'
import { Route as ProtectedContactsGoogleSheetsRouteImport } from './routes/_protected/contacts/google-sheets'
import { Route as ProtectedContactsImportReportRouteImport } from './routes/_protected/contacts/import-report'
import { Route as ProtectedContactsProfileRouteImport } from './routes/_protected/contacts/profile'
import { Route as ProtectedContactsSuppressionRouteImport } from './routes/_protected/contacts/suppression'
import { Route as ProtectedOrganizationIndexRouteImport } from './routes/_protected/organization/index'
import { Route as ProtectedOrganizationAccountSettingsRouteRouteImport } from './routes/_protected/organization/account-settings/route'
import { Route as ProtectedOrganizationNotificationsRouteImport } from './routes/_protected/organization/notifications'
import { Route as ProtectedOrganizationSecurityRouteImport } from './routes/_protected/organization/security'
import { Route as ProtectedOrganizationSettingsRouteImport } from './routes/_protected/organization/settings'
import { Route as ProtectedOrganizationTeamRouteRouteImport } from './routes/_protected/organization/team/route'
import { Route as ProtectedSupportIndexRouteImport } from './routes/_protected/support/index'
import { Route as ProtectedTemplatesIndexRouteImport } from './routes/_protected/templates/index'
import { Route as ProtectedTemplatesTemplateUuidRouteRouteImport } from './routes/_protected/templates/$templateUuid/route'
import { Route as ProtectedTemplatesNewRouteImport } from './routes/_protected/templates/new'
import { Route as ProtectedCampaignsCampaignUuidIndexRouteImport } from './routes/_protected/campaigns/$campaignUuid/index'
import { Route as ProtectedCampaignsCampaignUuidEditRouteImport } from './routes/_protected/campaigns/$campaignUuid/edit'
import { Route as ProtectedOrganizationAccountSettingsIndexRouteImport } from './routes/_protected/organization/account-settings/index'
import { Route as ProtectedOrganizationAccountSettingsActivityRouteImport } from './routes/_protected/organization/account-settings/activity'
import { Route as ProtectedOrganizationAccountSettingsApiIntegrationsRouteImport } from './routes/_protected/organization/account-settings/api-integrations'
import { Route as ProtectedOrganizationAccountSettingsBillingRouteImport } from './routes/_protected/organization/account-settings/billing'
import { Route as ProtectedOrganizationAccountSettingsEmailAccountsRouteImport } from './routes/_protected/organization/account-settings/email-accounts'
import { Route as ProtectedOrganizationAccountSettingsNotificationsRouteImport } from './routes/_protected/organization/account-settings/notifications'
import { Route as ProtectedOrganizationAccountSettingsPreferencesRouteImport } from './routes/_protected/organization/account-settings/preferences'
import { Route as ProtectedOrganizationAccountSettingsSecurityRouteImport } from './routes/_protected/organization/account-settings/security'
import { Route as ProtectedOrganizationTeamIndexRouteImport } from './routes/_protected/organization/team/index'
import { Route as ProtectedOrganizationTeamInviteRouteImport } from './routes/_protected/organization/team/invite'
import { Route as ProtectedOrganizationTeamRolesRouteImport } from './routes/_protected/organization/team/roles'
import { Route as ProtectedTemplatesTemplateUuidIndexRouteImport } from './routes/_protected/templates/$templateUuid/index'
import { Route as ProtectedTemplatesTemplateUuidEditRouteImport } from './routes/_protected/templates/$templateUuid/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessfulLoginRoute = SuccessfulLoginRouteImport.update({
  id: '/SuccessfulLogin',
  path: '/SuccessfulLogin',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRouteRoute = OnboardingRouteRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessForgotPasswordRoute = SuccessForgotPasswordRouteImport.update({
  id: '/successForgotPassword',
  path: '/successForgotPassword',
  getParentRoute: () => rootRouteImport,
} as any)
const Verify2faRoute = Verify2faRouteImport.update({
  id: '/verify-2fa',
  path: '/verify-2fa',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordIndexRoute = ForgotPasswordIndexRouteImport.update({
  id: '/ForgotPassword/',
  path: '/ForgotPassword/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordVerifyRoute = ForgotPasswordVerifyRouteImport.update({
  id: '/ForgotPassword/verify',
  path: '/ForgotPassword/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedCampaignsRouteRoute = ProtectedCampaignsRouteRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedOrganizationRouteRoute =
  ProtectedOrganizationRouteRouteImport.update({
    id: '/organization',
    path: '/organization',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedPendingInvitationRoute =
  ProtectedPendingInvitationRouteImport.update({
    id: '/pending-invitation',
    path: '/pending-invitation',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedTemplatesRouteRoute = ProtectedTemplatesRouteRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => ProtectedRoute,
} as any)
const InviteIndexRoute = InviteIndexRouteImport.update({
  id: '/invite/',
  path: '/invite/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteDeclineRoute = InviteDeclineRouteImport.update({
  id: '/invite/decline',
  path: '/invite/decline',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingOnboardingDetailsRoute =
  OnboardingOnboardingDetailsRouteImport.update({
    id: '/onboarding-details',
    path: '/onboarding-details',
    getParentRoute: () => OnboardingRouteRoute,
  } as any)
const OnboardingThemeSelectionRoute =
  OnboardingThemeSelectionRouteImport.update({
    id: '/themeSelection',
    path: '/themeSelection',
    getParentRoute: () => OnboardingRouteRoute,
  } as any)
const ProtectedAdminIndexRoute = ProtectedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedCampaignsIndexRoute = ProtectedCampaignsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedCampaignsRouteRoute,
} as any)
const ProtectedCampaignsCampaignUuidRouteRoute =
  ProtectedCampaignsCampaignUuidRouteRouteImport.update({
    id: '/$campaignUuid',
    path: '/$campaignUuid',
    getParentRoute: () => ProtectedCampaignsRouteRoute,
  } as any)
const ProtectedCampaignsNewRoute = ProtectedCampaignsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ProtectedCampaignsRouteRoute,
} as any)
const ProtectedContactsIndexRoute = ProtectedContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedContactsGoogleSheetsRoute =
  ProtectedContactsGoogleSheetsRouteImport.update({
    id: '/contacts/google-sheets',
    path: '/contacts/google-sheets',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedContactsImportReportRoute =
  ProtectedContactsImportReportRouteImport.update({
    id: '/contacts/import-report',
    path: '/contacts/import-report',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedContactsProfileRoute =
  ProtectedContactsProfileRouteImport.update({
    id: '/contacts/profile',
    path: '/contacts/profile',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedContactsSuppressionRoute =
  ProtectedContactsSuppressionRouteImport.update({
    id: '/contacts/suppression',
    path: '/contacts/suppression',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedOrganizationIndexRoute =
  ProtectedOrganizationIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedOrganizationRouteRoute,
  } as any)
const ProtectedOrganizationAccountSettingsRouteRoute =
  ProtectedOrganizationAccountSettingsRouteRouteImport.update({
    id: '/account-settings',
    path: '/account-settings',
    getParentRoute: () => ProtectedOrganizationRouteRoute,
  } as any)
const ProtectedOrganizationNotificationsRoute =
  ProtectedOrganizationNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => ProtectedOrganizationRouteRoute,
  } as any)
const ProtectedOrganizationSecurityRoute =
  ProtectedOrganizationSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => ProtectedOrganizationRouteRoute,
  } as any)
const ProtectedOrganizationSettingsRoute =
  ProtectedOrganizationSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ProtectedOrganizationRouteRoute,
  } as any)
const ProtectedOrganizationTeamRouteRoute =
  ProtectedOrganizationTeamRouteRouteImport.update({
    id: '/team',
    path: '/team',
    getParentRoute: () => ProtectedOrganizationRouteRoute,
  } as any)
const ProtectedSupportIndexRoute = ProtectedSupportIndexRouteImport.update({
  id: '/support/',
  path: '/support/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedTemplatesIndexRoute = ProtectedTemplatesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedTemplatesRouteRoute,
} as any)
const ProtectedTemplatesTemplateUuidRouteRoute =
  ProtectedTemplatesTemplateUuidRouteRouteImport.update({
    id: '/$templateUuid',
    path: '/$templateUuid',
    getParentRoute: () => ProtectedTemplatesRouteRoute,
  } as any)
const ProtectedTemplatesNewRoute = ProtectedTemplatesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ProtectedTemplatesRouteRoute,
} as any)
const ProtectedCampaignsCampaignUuidIndexRoute =
  ProtectedCampaignsCampaignUuidIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedCampaignsCampaignUuidRouteRoute,
  } as any)
const ProtectedCampaignsCampaignUuidEditRoute =
  ProtectedCampaignsCampaignUuidEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => ProtectedCampaignsCampaignUuidRouteRoute,
  } as any)
const ProtectedOrganizationAccountSettingsIndexRoute =
  ProtectedOrganizationAccountSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedOrganizationAccountSettingsRouteRoute,
  } as any)
const ProtectedOrganizationAccountSettingsActivityRoute =
  ProtectedOrganizationAccountSettingsActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => ProtectedOrganizationAccountSettingsRouteRoute,
  } as any)
const ProtectedOrganizationAccountSettingsApiIntegrationsRoute =
  ProtectedOrganizationAccountSettingsApiIntegrationsRouteImport.update({
    id: '/api-integrations',
    path: '/api-integrations',
    getParentRoute: () => ProtectedOrganizationAccountSettingsRouteRoute,
  } as any)
const ProtectedOrganizationAccountSettingsBillingRoute =
  ProtectedOrganizationAccountSettingsBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => ProtectedOrganizationAccountSettingsRouteRoute,
  } as any)
const ProtectedOrganizationAccountSettingsEmailAccountsRoute =
  ProtectedOrganizationAccountSettingsEmailAccountsRouteImport.update({
    id: '/email-accounts',
    path: '/email-accounts',
    getParentRoute: () => ProtectedOrganizationAccountSettingsRouteRoute,
  } as any)
const ProtectedOrganizationAccountSettingsNotificationsRoute =
  ProtectedOrganizationAccountSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => ProtectedOrganizationAccountSettingsRouteRoute,
  } as any)
const ProtectedOrganizationAccountSettingsPreferencesRoute =
  ProtectedOrganizationAccountSettingsPreferencesRouteImport.update({
    id: '/preferences',
    path: '/preferences',
    getParentRoute: () => ProtectedOrganizationAccountSettingsRouteRoute,
  } as any)
const ProtectedOrganizationAccountSettingsSecurityRoute =
  ProtectedOrganizationAccountSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => ProtectedOrganizationAccountSettingsRouteRoute,
  } as any)
const ProtectedOrganizationTeamIndexRoute =
  ProtectedOrganizationTeamIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedOrganizationTeamRouteRoute,
  } as any)
const ProtectedOrganizationTeamInviteRoute =
  ProtectedOrganizationTeamInviteRouteImport.update({
    id: '/invite',
    path: '/invite',
    getParentRoute: () => ProtectedOrganizationTeamRouteRoute,
  } as any)
const ProtectedOrganizationTeamRolesRoute =
  ProtectedOrganizationTeamRolesRouteImport.update({
    id: '/roles',
    path: '/roles',
    getParentRoute: () => ProtectedOrganizationTeamRouteRoute,
  } as any)
const ProtectedTemplatesTemplateUuidIndexRoute =
  ProtectedTemplatesTemplateUuidIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedTemplatesTemplateUuidRouteRoute,
  } as any)
const ProtectedTemplatesTemplateUuidEditRoute =
  ProtectedTemplatesTemplateUuidEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => ProtectedTemplatesTemplateUuidRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/SuccessfulLogin': typeof SuccessfulLoginRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/successForgotPassword': typeof SuccessForgotPasswordRoute
  '/verify-2fa': typeof Verify2faRoute
  '/verify-email': typeof VerifyEmailRoute
  '/campaigns': typeof ProtectedCampaignsRouteRouteWithChildren
  '/organization': typeof ProtectedOrganizationRouteRouteWithChildren
  '/templates': typeof ProtectedTemplatesRouteRouteWithChildren
  '/ForgotPassword/verify': typeof ForgotPasswordVerifyRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/pending-invitation': typeof ProtectedPendingInvitationRoute
  '/invite/decline': typeof InviteDeclineRoute
  '/onboarding/onboarding-details': typeof OnboardingOnboardingDetailsRoute
  '/onboarding/themeSelection': typeof OnboardingThemeSelectionRoute
  '/ForgotPassword/': typeof ForgotPasswordIndexRoute
  '/invite/': typeof InviteIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/campaigns/$campaignUuid': typeof ProtectedCampaignsCampaignUuidRouteRouteWithChildren
  '/organization/account-settings': typeof ProtectedOrganizationAccountSettingsRouteRouteWithChildren
  '/organization/team': typeof ProtectedOrganizationTeamRouteRouteWithChildren
  '/templates/$templateUuid': typeof ProtectedTemplatesTemplateUuidRouteRouteWithChildren
  '/campaigns/new': typeof ProtectedCampaignsNewRoute
  '/contacts/google-sheets': typeof ProtectedContactsGoogleSheetsRoute
  '/contacts/import-report': typeof ProtectedContactsImportReportRoute
  '/contacts/profile': typeof ProtectedContactsProfileRoute
  '/contacts/suppression': typeof ProtectedContactsSuppressionRoute
  '/organization/notifications': typeof ProtectedOrganizationNotificationsRoute
  '/organization/security': typeof ProtectedOrganizationSecurityRoute
  '/organization/settings': typeof ProtectedOrganizationSettingsRoute
  '/templates/new': typeof ProtectedTemplatesNewRoute
  '/admin/': typeof ProtectedAdminIndexRoute
  '/campaigns/': typeof ProtectedCampaignsIndexRoute
  '/contacts/': typeof ProtectedContactsIndexRoute
  '/organization/': typeof ProtectedOrganizationIndexRoute
  '/support/': typeof ProtectedSupportIndexRoute
  '/templates/': typeof ProtectedTemplatesIndexRoute
  '/campaigns/$campaignUuid/edit': typeof ProtectedCampaignsCampaignUuidEditRoute
  '/organization/account-settings/activity': typeof ProtectedOrganizationAccountSettingsActivityRoute
  '/organization/account-settings/api-integrations': typeof ProtectedOrganizationAccountSettingsApiIntegrationsRoute
  '/organization/account-settings/billing': typeof ProtectedOrganizationAccountSettingsBillingRoute
  '/organization/account-settings/email-accounts': typeof ProtectedOrganizationAccountSettingsEmailAccountsRoute
  '/organization/account-settings/notifications': typeof ProtectedOrganizationAccountSettingsNotificationsRoute
  '/organization/account-settings/preferences': typeof ProtectedOrganizationAccountSettingsPreferencesRoute
  '/organization/account-settings/security': typeof ProtectedOrganizationAccountSettingsSecurityRoute
  '/organization/team/invite': typeof ProtectedOrganizationTeamInviteRoute
  '/organization/team/roles': typeof ProtectedOrganizationTeamRolesRoute
  '/templates/$templateUuid/edit': typeof ProtectedTemplatesTemplateUuidEditRoute
  '/campaigns/$campaignUuid/': typeof ProtectedCampaignsCampaignUuidIndexRoute
  '/organization/account-settings/': typeof ProtectedOrganizationAccountSettingsIndexRoute
  '/organization/team/': typeof ProtectedOrganizationTeamIndexRoute
  '/templates/$templateUuid/': typeof ProtectedTemplatesTemplateUuidIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/SuccessfulLogin': typeof SuccessfulLoginRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/successForgotPassword': typeof SuccessForgotPasswordRoute
  '/verify-2fa': typeof Verify2faRoute
  '/verify-email': typeof VerifyEmailRoute
  '/ForgotPassword/verify': typeof ForgotPasswordVerifyRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/pending-invitation': typeof ProtectedPendingInvitationRoute
  '/invite/decline': typeof InviteDeclineRoute
  '/onboarding/onboarding-details': typeof OnboardingOnboardingDetailsRoute
  '/onboarding/themeSelection': typeof OnboardingThemeSelectionRoute
  '/ForgotPassword': typeof ForgotPasswordIndexRoute
  '/invite': typeof InviteIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/campaigns/new': typeof ProtectedCampaignsNewRoute
  '/contacts/google-sheets': typeof ProtectedContactsGoogleSheetsRoute
  '/contacts/import-report': typeof ProtectedContactsImportReportRoute
  '/contacts/profile': typeof ProtectedContactsProfileRoute
  '/contacts/suppression': typeof ProtectedContactsSuppressionRoute
  '/organization/notifications': typeof ProtectedOrganizationNotificationsRoute
  '/organization/security': typeof ProtectedOrganizationSecurityRoute
  '/organization/settings': typeof ProtectedOrganizationSettingsRoute
  '/templates/new': typeof ProtectedTemplatesNewRoute
  '/admin': typeof ProtectedAdminIndexRoute
  '/campaigns': typeof ProtectedCampaignsIndexRoute
  '/contacts': typeof ProtectedContactsIndexRoute
  '/organization': typeof ProtectedOrganizationIndexRoute
  '/support': typeof ProtectedSupportIndexRoute
  '/templates': typeof ProtectedTemplatesIndexRoute
  '/campaigns/$campaignUuid/edit': typeof ProtectedCampaignsCampaignUuidEditRoute
  '/organization/account-settings/activity': typeof ProtectedOrganizationAccountSettingsActivityRoute
  '/organization/account-settings/api-integrations': typeof ProtectedOrganizationAccountSettingsApiIntegrationsRoute
  '/organization/account-settings/billing': typeof ProtectedOrganizationAccountSettingsBillingRoute
  '/organization/account-settings/email-accounts': typeof ProtectedOrganizationAccountSettingsEmailAccountsRoute
  '/organization/account-settings/notifications': typeof ProtectedOrganizationAccountSettingsNotificationsRoute
  '/organization/account-settings/preferences': typeof ProtectedOrganizationAccountSettingsPreferencesRoute
  '/organization/account-settings/security': typeof ProtectedOrganizationAccountSettingsSecurityRoute
  '/organization/team/invite': typeof ProtectedOrganizationTeamInviteRoute
  '/organization/team/roles': typeof ProtectedOrganizationTeamRolesRoute
  '/templates/$templateUuid/edit': typeof ProtectedTemplatesTemplateUuidEditRoute
  '/campaigns/$campaignUuid': typeof ProtectedCampaignsCampaignUuidIndexRoute
  '/organization/account-settings': typeof ProtectedOrganizationAccountSettingsIndexRoute
  '/organization/team': typeof ProtectedOrganizationTeamIndexRoute
  '/templates/$templateUuid': typeof ProtectedTemplatesTemplateUuidIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/SuccessfulLogin': typeof SuccessfulLoginRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/successForgotPassword': typeof SuccessForgotPasswordRoute
  '/verify-2fa': typeof Verify2faRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_protected/campaigns': typeof ProtectedCampaignsRouteRouteWithChildren
  '/_protected/organization': typeof ProtectedOrganizationRouteRouteWithChildren
  '/_protected/templates': typeof ProtectedTemplatesRouteRouteWithChildren
  '/ForgotPassword/verify': typeof ForgotPasswordVerifyRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/pending-invitation': typeof ProtectedPendingInvitationRoute
  '/invite/decline': typeof InviteDeclineRoute
  '/onboarding/onboarding-details': typeof OnboardingOnboardingDetailsRoute
  '/onboarding/themeSelection': typeof OnboardingThemeSelectionRoute
  '/ForgotPassword/': typeof ForgotPasswordIndexRoute
  '/invite/': typeof InviteIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/_protected/campaigns/$campaignUuid': typeof ProtectedCampaignsCampaignUuidRouteRouteWithChildren
  '/_protected/organization/account-settings': typeof ProtectedOrganizationAccountSettingsRouteRouteWithChildren
  '/_protected/organization/team': typeof ProtectedOrganizationTeamRouteRouteWithChildren
  '/_protected/templates/$templateUuid': typeof ProtectedTemplatesTemplateUuidRouteRouteWithChildren
  '/_protected/campaigns/new': typeof ProtectedCampaignsNewRoute
  '/_protected/contacts/google-sheets': typeof ProtectedContactsGoogleSheetsRoute
  '/_protected/contacts/import-report': typeof ProtectedContactsImportReportRoute
  '/_protected/contacts/profile': typeof ProtectedContactsProfileRoute
  '/_protected/contacts/suppression': typeof ProtectedContactsSuppressionRoute
  '/_protected/organization/notifications': typeof ProtectedOrganizationNotificationsRoute
  '/_protected/organization/security': typeof ProtectedOrganizationSecurityRoute
  '/_protected/organization/settings': typeof ProtectedOrganizationSettingsRoute
  '/_protected/templates/new': typeof ProtectedTemplatesNewRoute
  '/_protected/admin/': typeof ProtectedAdminIndexRoute
  '/_protected/campaigns/': typeof ProtectedCampaignsIndexRoute
  '/_protected/contacts/': typeof ProtectedContactsIndexRoute
  '/_protected/organization/': typeof ProtectedOrganizationIndexRoute
  '/_protected/support/': typeof ProtectedSupportIndexRoute
  '/_protected/templates/': typeof ProtectedTemplatesIndexRoute
  '/_protected/campaigns/$campaignUuid/edit': typeof ProtectedCampaignsCampaignUuidEditRoute
  '/_protected/organization/account-settings/activity': typeof ProtectedOrganizationAccountSettingsActivityRoute
  '/_protected/organization/account-settings/api-integrations': typeof ProtectedOrganizationAccountSettingsApiIntegrationsRoute
  '/_protected/organization/account-settings/billing': typeof ProtectedOrganizationAccountSettingsBillingRoute
  '/_protected/organization/account-settings/email-accounts': typeof ProtectedOrganizationAccountSettingsEmailAccountsRoute
  '/_protected/organization/account-settings/notifications': typeof ProtectedOrganizationAccountSettingsNotificationsRoute
  '/_protected/organization/account-settings/preferences': typeof ProtectedOrganizationAccountSettingsPreferencesRoute
  '/_protected/organization/account-settings/security': typeof ProtectedOrganizationAccountSettingsSecurityRoute
  '/_protected/organization/team/invite': typeof ProtectedOrganizationTeamInviteRoute
  '/_protected/organization/team/roles': typeof ProtectedOrganizationTeamRolesRoute
  '/_protected/templates/$templateUuid/edit': typeof ProtectedTemplatesTemplateUuidEditRoute
  '/_protected/campaigns/$campaignUuid/': typeof ProtectedCampaignsCampaignUuidIndexRoute
  '/_protected/organization/account-settings/': typeof ProtectedOrganizationAccountSettingsIndexRoute
  '/_protected/organization/team/': typeof ProtectedOrganizationTeamIndexRoute
  '/_protected/templates/$templateUuid/': typeof ProtectedTemplatesTemplateUuidIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/SuccessfulLogin'
    | '/login'
    | '/register'
    | '/successForgotPassword'
    | '/verify-2fa'
    | '/verify-email'
    | '/campaigns'
    | '/organization'
    | '/templates'
    | '/ForgotPassword/verify'
    | '/dashboard'
    | '/pending-invitation'
    | '/invite/decline'
    | '/onboarding/onboarding-details'
    | '/onboarding/themeSelection'
    | '/ForgotPassword/'
    | '/invite/'
    | '/onboarding/'
    | '/campaigns/$campaignUuid'
    | '/organization/account-settings'
    | '/organization/team'
    | '/templates/$templateUuid'
    | '/campaigns/new'
    | '/contacts/google-sheets'
    | '/contacts/import-report'
    | '/contacts/profile'
    | '/contacts/suppression'
    | '/organization/notifications'
    | '/organization/security'
    | '/organization/settings'
    | '/templates/new'
    | '/admin/'
    | '/campaigns/'
    | '/contacts/'
    | '/organization/'
    | '/support/'
    | '/templates/'
    | '/campaigns/$campaignUuid/edit'
    | '/organization/account-settings/activity'
    | '/organization/account-settings/api-integrations'
    | '/organization/account-settings/billing'
    | '/organization/account-settings/email-accounts'
    | '/organization/account-settings/notifications'
    | '/organization/account-settings/preferences'
    | '/organization/account-settings/security'
    | '/organization/team/invite'
    | '/organization/team/roles'
    | '/templates/$templateUuid/edit'
    | '/campaigns/$campaignUuid/'
    | '/organization/account-settings/'
    | '/organization/team/'
    | '/templates/$templateUuid/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/SuccessfulLogin'
    | '/login'
    | '/register'
    | '/successForgotPassword'
    | '/verify-2fa'
    | '/verify-email'
    | '/ForgotPassword/verify'
    | '/dashboard'
    | '/pending-invitation'
    | '/invite/decline'
    | '/onboarding/onboarding-details'
    | '/onboarding/themeSelection'
    | '/ForgotPassword'
    | '/invite'
    | '/onboarding'
    | '/campaigns/new'
    | '/contacts/google-sheets'
    | '/contacts/import-report'
    | '/contacts/profile'
    | '/contacts/suppression'
    | '/organization/notifications'
    | '/organization/security'
    | '/organization/settings'
    | '/templates/new'
    | '/admin'
    | '/campaigns'
    | '/contacts'
    | '/organization'
    | '/support'
    | '/templates'
    | '/campaigns/$campaignUuid/edit'
    | '/organization/account-settings/activity'
    | '/organization/account-settings/api-integrations'
    | '/organization/account-settings/billing'
    | '/organization/account-settings/email-accounts'
    | '/organization/account-settings/notifications'
    | '/organization/account-settings/preferences'
    | '/organization/account-settings/security'
    | '/organization/team/invite'
    | '/organization/team/roles'
    | '/templates/$templateUuid/edit'
    | '/campaigns/$campaignUuid'
    | '/organization/account-settings'
    | '/organization/team'
    | '/templates/$templateUuid'
  id:
    | '__root__'
    | '/'
    | '/onboarding'
    | '/SuccessfulLogin'
    | '/_protected'
    | '/login'
    | '/register'
    | '/successForgotPassword'
    | '/verify-2fa'
    | '/verify-email'
    | '/_protected/campaigns'
    | '/_protected/organization'
    | '/_protected/templates'
    | '/ForgotPassword/verify'
    | '/_protected/dashboard'
    | '/_protected/pending-invitation'
    | '/invite/decline'
    | '/onboarding/onboarding-details'
    | '/onboarding/themeSelection'
    | '/ForgotPassword/'
    | '/invite/'
    | '/onboarding/'
    | '/_protected/campaigns/$campaignUuid'
    | '/_protected/organization/account-settings'
    | '/_protected/organization/team'
    | '/_protected/templates/$templateUuid'
    | '/_protected/campaigns/new'
    | '/_protected/contacts/google-sheets'
    | '/_protected/contacts/import-report'
    | '/_protected/contacts/profile'
    | '/_protected/contacts/suppression'
    | '/_protected/organization/notifications'
    | '/_protected/organization/security'
    | '/_protected/organization/settings'
    | '/_protected/templates/new'
    | '/_protected/admin/'
    | '/_protected/campaigns/'
    | '/_protected/contacts/'
    | '/_protected/organization/'
    | '/_protected/support/'
    | '/_protected/templates/'
    | '/_protected/campaigns/$campaignUuid/edit'
    | '/_protected/organization/account-settings/activity'
    | '/_protected/organization/account-settings/api-integrations'
    | '/_protected/organization/account-settings/billing'
    | '/_protected/organization/account-settings/email-accounts'
    | '/_protected/organization/account-settings/notifications'
    | '/_protected/organization/account-settings/preferences'
    | '/_protected/organization/account-settings/security'
    | '/_protected/organization/team/invite'
    | '/_protected/organization/team/roles'
    | '/_protected/templates/$templateUuid/edit'
    | '/_protected/campaigns/$campaignUuid/'
    | '/_protected/organization/account-settings/'
    | '/_protected/organization/team/'
    | '/_protected/templates/$templateUuid/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OnboardingRouteRoute: typeof OnboardingRouteRouteWithChildren
  SuccessfulLoginRoute: typeof SuccessfulLoginRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SuccessForgotPasswordRoute: typeof SuccessForgotPasswordRoute
  Verify2faRoute: typeof Verify2faRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  ForgotPasswordVerifyRoute: typeof ForgotPasswordVerifyRoute
  InviteDeclineRoute: typeof InviteDeclineRoute
  ForgotPasswordIndexRoute: typeof ForgotPasswordIndexRoute
  InviteIndexRoute: typeof InviteIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/SuccessfulLogin': {
      id: '/SuccessfulLogin'
      path: '/SuccessfulLogin'
      fullPath: '/SuccessfulLogin'
      preLoaderRoute: typeof SuccessfulLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/successForgotPassword': {
      id: '/successForgotPassword'
      path: '/successForgotPassword'
      fullPath: '/successForgotPassword'
      preLoaderRoute: typeof SuccessForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-2fa': {
      id: '/verify-2fa'
      path: '/verify-2fa'
      fullPath: '/verify-2fa'
      preLoaderRoute: typeof Verify2faRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ForgotPassword/': {
      id: '/ForgotPassword/'
      path: '/ForgotPassword'
      fullPath: '/ForgotPassword/'
      preLoaderRoute: typeof ForgotPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ForgotPassword/verify': {
      id: '/ForgotPassword/verify'
      path: '/ForgotPassword/verify'
      fullPath: '/ForgotPassword/verify'
      preLoaderRoute: typeof ForgotPasswordVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/campaigns': {
      id: '/_protected/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof ProtectedCampaignsRouteRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/organization': {
      id: '/_protected/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof ProtectedOrganizationRouteRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/pending-invitation': {
      id: '/_protected/pending-invitation'
      path: '/pending-invitation'
      fullPath: '/pending-invitation'
      preLoaderRoute: typeof ProtectedPendingInvitationRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/templates': {
      id: '/_protected/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof ProtectedTemplatesRouteRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/invite/': {
      id: '/invite/'
      path: '/invite'
      fullPath: '/invite/'
      preLoaderRoute: typeof InviteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/decline': {
      id: '/invite/decline'
      path: '/invite/decline'
      fullPath: '/invite/decline'
      preLoaderRoute: typeof InviteDeclineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/onboarding-details': {
      id: '/onboarding/onboarding-details'
      path: '/onboarding-details'
      fullPath: '/onboarding/onboarding-details'
      preLoaderRoute: typeof OnboardingOnboardingDetailsRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/themeSelection': {
      id: '/onboarding/themeSelection'
      path: '/themeSelection'
      fullPath: '/onboarding/themeSelection'
      preLoaderRoute: typeof OnboardingThemeSelectionRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/_protected/admin/': {
      id: '/_protected/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof ProtectedAdminIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/campaigns/': {
      id: '/_protected/campaigns/'
      path: '/'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof ProtectedCampaignsIndexRouteImport
      parentRoute: typeof ProtectedCampaignsRouteRoute
    }
    '/_protected/campaigns/$campaignUuid': {
      id: '/_protected/campaigns/$campaignUuid'
      path: '/$campaignUuid'
      fullPath: '/campaigns/$campaignUuid'
      preLoaderRoute: typeof ProtectedCampaignsCampaignUuidRouteRouteImport
      parentRoute: typeof ProtectedCampaignsRouteRoute
    }
    '/_protected/campaigns/new': {
      id: '/_protected/campaigns/new'
      path: '/new'
      fullPath: '/campaigns/new'
      preLoaderRoute: typeof ProtectedCampaignsNewRouteImport
      parentRoute: typeof ProtectedCampaignsRouteRoute
    }
    '/_protected/contacts/': {
      id: '/_protected/contacts/'
      path: '/contacts'
      fullPath: '/contacts/'
      preLoaderRoute: typeof ProtectedContactsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/contacts/google-sheets': {
      id: '/_protected/contacts/google-sheets'
      path: '/contacts/google-sheets'
      fullPath: '/contacts/google-sheets'
      preLoaderRoute: typeof ProtectedContactsGoogleSheetsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/contacts/import-report': {
      id: '/_protected/contacts/import-report'
      path: '/contacts/import-report'
      fullPath: '/contacts/import-report'
      preLoaderRoute: typeof ProtectedContactsImportReportRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/contacts/profile': {
      id: '/_protected/contacts/profile'
      path: '/contacts/profile'
      fullPath: '/contacts/profile'
      preLoaderRoute: typeof ProtectedContactsProfileRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/contacts/suppression': {
      id: '/_protected/contacts/suppression'
      path: '/contacts/suppression'
      fullPath: '/contacts/suppression'
      preLoaderRoute: typeof ProtectedContactsSuppressionRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/organization/': {
      id: '/_protected/organization/'
      path: '/'
      fullPath: '/organization/'
      preLoaderRoute: typeof ProtectedOrganizationIndexRouteImport
      parentRoute: typeof ProtectedOrganizationRouteRoute
    }
    '/_protected/organization/account-settings': {
      id: '/_protected/organization/account-settings'
      path: '/account-settings'
      fullPath: '/organization/account-settings'
      preLoaderRoute: typeof ProtectedOrganizationAccountSettingsRouteRouteImport
      parentRoute: typeof ProtectedOrganizationRouteRoute
    }
    '/_protected/organization/notifications': {
      id: '/_protected/organization/notifications'
      path: '/notifications'
      fullPath: '/organization/notifications'
      preLoaderRoute: typeof ProtectedOrganizationNotificationsRouteImport
      parentRoute: typeof ProtectedOrganizationRouteRoute
    }
    '/_protected/organization/security': {
      id: '/_protected/organization/security'
      path: '/security'
      fullPath: '/organization/security'
      preLoaderRoute: typeof ProtectedOrganizationSecurityRouteImport
      parentRoute: typeof ProtectedOrganizationRouteRoute
    }
    '/_protected/organization/settings': {
      id: '/_protected/organization/settings'
      path: '/settings'
      fullPath: '/organization/settings'
      preLoaderRoute: typeof ProtectedOrganizationSettingsRouteImport
      parentRoute: typeof ProtectedOrganizationRouteRoute
    }
    '/_protected/organization/team': {
      id: '/_protected/organization/team'
      path: '/team'
      fullPath: '/organization/team'
      preLoaderRoute: typeof ProtectedOrganizationTeamRouteRouteImport
      parentRoute: typeof ProtectedOrganizationRouteRoute
    }
    '/_protected/support/': {
      id: '/_protected/support/'
      path: '/support'
      fullPath: '/support/'
      preLoaderRoute: typeof ProtectedSupportIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/templates/': {
      id: '/_protected/templates/'
      path: '/'
      fullPath: '/templates/'
      preLoaderRoute: typeof ProtectedTemplatesIndexRouteImport
      parentRoute: typeof ProtectedTemplatesRouteRoute
    }
    '/_protected/templates/$templateUuid': {
      id: '/_protected/templates/$templateUuid'
      path: '/$templateUuid'
      fullPath: '/templates/$templateUuid'
      preLoaderRoute: typeof ProtectedTemplatesTemplateUuidRouteRouteImport
      parentRoute: typeof ProtectedTemplatesRouteRoute
    }
    '/_protected/templates/new': {
      id: '/_protected/templates/new'
      path: '/new'
      fullPath: '/templates/new'
      preLoaderRoute: typeof ProtectedTemplatesNewRouteImport
      parentRoute: typeof ProtectedTemplatesRouteRoute
    }
    '/_protected/campaigns/$campaignUuid/': {
      id: '/_protected/campaigns/$campaignUuid/'
      path: '/'
      fullPath: '/campaigns/$campaignUuid/'
      preLoaderRoute: typeof ProtectedCampaignsCampaignUuidIndexRouteImport
      parentRoute: typeof ProtectedCampaignsCampaignUuidRouteRoute
    }
    '/_protected/campaigns/$campaignUuid/edit': {
      id: '/_protected/campaigns/$campaignUuid/edit'
      path: '/edit'
      fullPath: '/campaigns/$campaignUuid/edit'
      preLoaderRoute: typeof ProtectedCampaignsCampaignUuidEditRouteImport
      parentRoute: typeof ProtectedCampaignsCampaignUuidRouteRoute
    }
    '/_protected/organization/account-settings/': {
      id: '/_protected/organization/account-settings/'
      path: '/'
      fullPath: '/organization/account-settings/'
      preLoaderRoute: typeof ProtectedOrganizationAccountSettingsIndexRouteImport
      parentRoute: typeof ProtectedOrganizationAccountSettingsRouteRoute
    }
    '/_protected/organization/account-settings/activity': {
      id: '/_protected/organization/account-settings/activity'
      path: '/activity'
      fullPath: '/organization/account-settings/activity'
      preLoaderRoute: typeof ProtectedOrganizationAccountSettingsActivityRouteImport
      parentRoute: typeof ProtectedOrganizationAccountSettingsRouteRoute
    }
    '/_protected/organization/account-settings/api-integrations': {
      id: '/_protected/organization/account-settings/api-integrations'
      path: '/api-integrations'
      fullPath: '/organization/account-settings/api-integrations'
      preLoaderRoute: typeof ProtectedOrganizationAccountSettingsApiIntegrationsRouteImport
      parentRoute: typeof ProtectedOrganizationAccountSettingsRouteRoute
    }
    '/_protected/organization/account-settings/billing': {
      id: '/_protected/organization/account-settings/billing'
      path: '/billing'
      fullPath: '/organization/account-settings/billing'
      preLoaderRoute: typeof ProtectedOrganizationAccountSettingsBillingRouteImport
      parentRoute: typeof ProtectedOrganizationAccountSettingsRouteRoute
    }
    '/_protected/organization/account-settings/email-accounts': {
      id: '/_protected/organization/account-settings/email-accounts'
      path: '/email-accounts'
      fullPath: '/organization/account-settings/email-accounts'
      preLoaderRoute: typeof ProtectedOrganizationAccountSettingsEmailAccountsRouteImport
      parentRoute: typeof ProtectedOrganizationAccountSettingsRouteRoute
    }
    '/_protected/organization/account-settings/notifications': {
      id: '/_protected/organization/account-settings/notifications'
      path: '/notifications'
      fullPath: '/organization/account-settings/notifications'
      preLoaderRoute: typeof ProtectedOrganizationAccountSettingsNotificationsRouteImport
      parentRoute: typeof ProtectedOrganizationAccountSettingsRouteRoute
    }
    '/_protected/organization/account-settings/preferences': {
      id: '/_protected/organization/account-settings/preferences'
      path: '/preferences'
      fullPath: '/organization/account-settings/preferences'
      preLoaderRoute: typeof ProtectedOrganizationAccountSettingsPreferencesRouteImport
      parentRoute: typeof ProtectedOrganizationAccountSettingsRouteRoute
    }
    '/_protected/organization/account-settings/security': {
      id: '/_protected/organization/account-settings/security'
      path: '/security'
      fullPath: '/organization/account-settings/security'
      preLoaderRoute: typeof ProtectedOrganizationAccountSettingsSecurityRouteImport
      parentRoute: typeof ProtectedOrganizationAccountSettingsRouteRoute
    }
    '/_protected/organization/team/': {
      id: '/_protected/organization/team/'
      path: '/'
      fullPath: '/organization/team/'
      preLoaderRoute: typeof ProtectedOrganizationTeamIndexRouteImport
      parentRoute: typeof ProtectedOrganizationTeamRouteRoute
    }
    '/_protected/organization/team/invite': {
      id: '/_protected/organization/team/invite'
      path: '/invite'
      fullPath: '/organization/team/invite'
      preLoaderRoute: typeof ProtectedOrganizationTeamInviteRouteImport
      parentRoute: typeof ProtectedOrganizationTeamRouteRoute
    }
    '/_protected/organization/team/roles': {
      id: '/_protected/organization/team/roles'
      path: '/roles'
      fullPath: '/organization/team/roles'
      preLoaderRoute: typeof ProtectedOrganizationTeamRolesRouteImport
      parentRoute: typeof ProtectedOrganizationTeamRouteRoute
    }
    '/_protected/templates/$templateUuid/': {
      id: '/_protected/templates/$templateUuid/'
      path: '/'
      fullPath: '/templates/$templateUuid/'
      preLoaderRoute: typeof ProtectedTemplatesTemplateUuidIndexRouteImport
      parentRoute: typeof ProtectedTemplatesTemplateUuidRouteRoute
    }
    '/_protected/templates/$templateUuid/edit': {
      id: '/_protected/templates/$templateUuid/edit'
      path: '/edit'
      fullPath: '/templates/$templateUuid/edit'
      preLoaderRoute: typeof ProtectedTemplatesTemplateUuidEditRouteImport
      parentRoute: typeof ProtectedTemplatesTemplateUuidRouteRoute
    }
  }
}

interface OnboardingRouteRouteChildren {
  OnboardingOnboardingDetailsRoute: typeof OnboardingOnboardingDetailsRoute
  OnboardingThemeSelectionRoute: typeof OnboardingThemeSelectionRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const OnboardingRouteRouteChildren: OnboardingRouteRouteChildren = {
  OnboardingOnboardingDetailsRoute: OnboardingOnboardingDetailsRoute,
  OnboardingThemeSelectionRoute: OnboardingThemeSelectionRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}

const OnboardingRouteRouteWithChildren = OnboardingRouteRoute._addFileChildren(
  OnboardingRouteRouteChildren,
)

interface ProtectedCampaignsCampaignUuidRouteRouteChildren {
  ProtectedCampaignsCampaignUuidEditRoute: typeof ProtectedCampaignsCampaignUuidEditRoute
  ProtectedCampaignsCampaignUuidIndexRoute: typeof ProtectedCampaignsCampaignUuidIndexRoute
}

const ProtectedCampaignsCampaignUuidRouteRouteChildren: ProtectedCampaignsCampaignUuidRouteRouteChildren =
  {
    ProtectedCampaignsCampaignUuidEditRoute:
      ProtectedCampaignsCampaignUuidEditRoute,
    ProtectedCampaignsCampaignUuidIndexRoute:
      ProtectedCampaignsCampaignUuidIndexRoute,
  }

const ProtectedCampaignsCampaignUuidRouteRouteWithChildren =
  ProtectedCampaignsCampaignUuidRouteRoute._addFileChildren(
    ProtectedCampaignsCampaignUuidRouteRouteChildren,
  )

interface ProtectedCampaignsRouteRouteChildren {
  ProtectedCampaignsCampaignUuidRouteRoute: typeof ProtectedCampaignsCampaignUuidRouteRouteWithChildren
  ProtectedCampaignsNewRoute: typeof ProtectedCampaignsNewRoute
  ProtectedCampaignsIndexRoute: typeof ProtectedCampaignsIndexRoute
}

const ProtectedCampaignsRouteRouteChildren: ProtectedCampaignsRouteRouteChildren =
  {
    ProtectedCampaignsCampaignUuidRouteRoute:
      ProtectedCampaignsCampaignUuidRouteRouteWithChildren,
    ProtectedCampaignsNewRoute: ProtectedCampaignsNewRoute,
    ProtectedCampaignsIndexRoute: ProtectedCampaignsIndexRoute,
  }

const ProtectedCampaignsRouteRouteWithChildren =
  ProtectedCampaignsRouteRoute._addFileChildren(
    ProtectedCampaignsRouteRouteChildren,
  )

interface ProtectedOrganizationAccountSettingsRouteRouteChildren {
  ProtectedOrganizationAccountSettingsActivityRoute: typeof ProtectedOrganizationAccountSettingsActivityRoute
  ProtectedOrganizationAccountSettingsApiIntegrationsRoute: typeof ProtectedOrganizationAccountSettingsApiIntegrationsRoute
  ProtectedOrganizationAccountSettingsBillingRoute: typeof ProtectedOrganizationAccountSettingsBillingRoute
  ProtectedOrganizationAccountSettingsEmailAccountsRoute: typeof ProtectedOrganizationAccountSettingsEmailAccountsRoute
  ProtectedOrganizationAccountSettingsNotificationsRoute: typeof ProtectedOrganizationAccountSettingsNotificationsRoute
  ProtectedOrganizationAccountSettingsPreferencesRoute: typeof ProtectedOrganizationAccountSettingsPreferencesRoute
  ProtectedOrganizationAccountSettingsSecurityRoute: typeof ProtectedOrganizationAccountSettingsSecurityRoute
  ProtectedOrganizationAccountSettingsIndexRoute: typeof ProtectedOrganizationAccountSettingsIndexRoute
}

const ProtectedOrganizationAccountSettingsRouteRouteChildren: ProtectedOrganizationAccountSettingsRouteRouteChildren =
  {
    ProtectedOrganizationAccountSettingsActivityRoute:
      ProtectedOrganizationAccountSettingsActivityRoute,
    ProtectedOrganizationAccountSettingsApiIntegrationsRoute:
      ProtectedOrganizationAccountSettingsApiIntegrationsRoute,
    ProtectedOrganizationAccountSettingsBillingRoute:
      ProtectedOrganizationAccountSettingsBillingRoute,
    ProtectedOrganizationAccountSettingsEmailAccountsRoute:
      ProtectedOrganizationAccountSettingsEmailAccountsRoute,
    ProtectedOrganizationAccountSettingsNotificationsRoute:
      ProtectedOrganizationAccountSettingsNotificationsRoute,
    ProtectedOrganizationAccountSettingsPreferencesRoute:
      ProtectedOrganizationAccountSettingsPreferencesRoute,
    ProtectedOrganizationAccountSettingsSecurityRoute:
      ProtectedOrganizationAccountSettingsSecurityRoute,
    ProtectedOrganizationAccountSettingsIndexRoute:
      ProtectedOrganizationAccountSettingsIndexRoute,
  }

const ProtectedOrganizationAccountSettingsRouteRouteWithChildren =
  ProtectedOrganizationAccountSettingsRouteRoute._addFileChildren(
    ProtectedOrganizationAccountSettingsRouteRouteChildren,
  )

interface ProtectedOrganizationTeamRouteRouteChildren {
  ProtectedOrganizationTeamInviteRoute: typeof ProtectedOrganizationTeamInviteRoute
  ProtectedOrganizationTeamRolesRoute: typeof ProtectedOrganizationTeamRolesRoute
  ProtectedOrganizationTeamIndexRoute: typeof ProtectedOrganizationTeamIndexRoute
}

const ProtectedOrganizationTeamRouteRouteChildren: ProtectedOrganizationTeamRouteRouteChildren =
  {
    ProtectedOrganizationTeamInviteRoute: ProtectedOrganizationTeamInviteRoute,
    ProtectedOrganizationTeamRolesRoute: ProtectedOrganizationTeamRolesRoute,
    ProtectedOrganizationTeamIndexRoute: ProtectedOrganizationTeamIndexRoute,
  }

const ProtectedOrganizationTeamRouteRouteWithChildren =
  ProtectedOrganizationTeamRouteRoute._addFileChildren(
    ProtectedOrganizationTeamRouteRouteChildren,
  )

interface ProtectedOrganizationRouteRouteChildren {
  ProtectedOrganizationAccountSettingsRouteRoute: typeof ProtectedOrganizationAccountSettingsRouteRouteWithChildren
  ProtectedOrganizationTeamRouteRoute: typeof ProtectedOrganizationTeamRouteRouteWithChildren
  ProtectedOrganizationNotificationsRoute: typeof ProtectedOrganizationNotificationsRoute
  ProtectedOrganizationSecurityRoute: typeof ProtectedOrganizationSecurityRoute
  ProtectedOrganizationSettingsRoute: typeof ProtectedOrganizationSettingsRoute
  ProtectedOrganizationIndexRoute: typeof ProtectedOrganizationIndexRoute
}

const ProtectedOrganizationRouteRouteChildren: ProtectedOrganizationRouteRouteChildren =
  {
    ProtectedOrganizationAccountSettingsRouteRoute:
      ProtectedOrganizationAccountSettingsRouteRouteWithChildren,
    ProtectedOrganizationTeamRouteRoute:
      ProtectedOrganizationTeamRouteRouteWithChildren,
    ProtectedOrganizationNotificationsRoute:
      ProtectedOrganizationNotificationsRoute,
    ProtectedOrganizationSecurityRoute: ProtectedOrganizationSecurityRoute,
    ProtectedOrganizationSettingsRoute: ProtectedOrganizationSettingsRoute,
    ProtectedOrganizationIndexRoute: ProtectedOrganizationIndexRoute,
  }

const ProtectedOrganizationRouteRouteWithChildren =
  ProtectedOrganizationRouteRoute._addFileChildren(
    ProtectedOrganizationRouteRouteChildren,
  )

interface ProtectedTemplatesTemplateUuidRouteRouteChildren {
  ProtectedTemplatesTemplateUuidEditRoute: typeof ProtectedTemplatesTemplateUuidEditRoute
  ProtectedTemplatesTemplateUuidIndexRoute: typeof ProtectedTemplatesTemplateUuidIndexRoute
}

const ProtectedTemplatesTemplateUuidRouteRouteChildren: ProtectedTemplatesTemplateUuidRouteRouteChildren =
  {
    ProtectedTemplatesTemplateUuidEditRoute:
      ProtectedTemplatesTemplateUuidEditRoute,
    ProtectedTemplatesTemplateUuidIndexRoute:
      ProtectedTemplatesTemplateUuidIndexRoute,
  }

const ProtectedTemplatesTemplateUuidRouteRouteWithChildren =
  ProtectedTemplatesTemplateUuidRouteRoute._addFileChildren(
    ProtectedTemplatesTemplateUuidRouteRouteChildren,
  )

interface ProtectedTemplatesRouteRouteChildren {
  ProtectedTemplatesTemplateUuidRouteRoute: typeof ProtectedTemplatesTemplateUuidRouteRouteWithChildren
  ProtectedTemplatesNewRoute: typeof ProtectedTemplatesNewRoute
  ProtectedTemplatesIndexRoute: typeof ProtectedTemplatesIndexRoute
}

const ProtectedTemplatesRouteRouteChildren: ProtectedTemplatesRouteRouteChildren =
  {
    ProtectedTemplatesTemplateUuidRouteRoute:
      ProtectedTemplatesTemplateUuidRouteRouteWithChildren,
    ProtectedTemplatesNewRoute: ProtectedTemplatesNewRoute,
    ProtectedTemplatesIndexRoute: ProtectedTemplatesIndexRoute,
  }

const ProtectedTemplatesRouteRouteWithChildren =
  ProtectedTemplatesRouteRoute._addFileChildren(
    ProtectedTemplatesRouteRouteChildren,
  )

interface ProtectedRouteChildren {
  ProtectedCampaignsRouteRoute: typeof ProtectedCampaignsRouteRouteWithChildren
  ProtectedOrganizationRouteRoute: typeof ProtectedOrganizationRouteRouteWithChildren
  ProtectedTemplatesRouteRoute: typeof ProtectedTemplatesRouteRouteWithChildren
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedPendingInvitationRoute: typeof ProtectedPendingInvitationRoute
  ProtectedContactsGoogleSheetsRoute: typeof ProtectedContactsGoogleSheetsRoute
  ProtectedContactsImportReportRoute: typeof ProtectedContactsImportReportRoute
  ProtectedContactsProfileRoute: typeof ProtectedContactsProfileRoute
  ProtectedContactsSuppressionRoute: typeof ProtectedContactsSuppressionRoute
  ProtectedAdminIndexRoute: typeof ProtectedAdminIndexRoute
  ProtectedContactsIndexRoute: typeof ProtectedContactsIndexRoute
  ProtectedSupportIndexRoute: typeof ProtectedSupportIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedCampaignsRouteRoute: ProtectedCampaignsRouteRouteWithChildren,
  ProtectedOrganizationRouteRoute: ProtectedOrganizationRouteRouteWithChildren,
  ProtectedTemplatesRouteRoute: ProtectedTemplatesRouteRouteWithChildren,
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedPendingInvitationRoute: ProtectedPendingInvitationRoute,
  ProtectedContactsGoogleSheetsRoute: ProtectedContactsGoogleSheetsRoute,
  ProtectedContactsImportReportRoute: ProtectedContactsImportReportRoute,
  ProtectedContactsProfileRoute: ProtectedContactsProfileRoute,
  ProtectedContactsSuppressionRoute: ProtectedContactsSuppressionRoute,
  ProtectedAdminIndexRoute: ProtectedAdminIndexRoute,
  ProtectedContactsIndexRoute: ProtectedContactsIndexRoute,
  ProtectedSupportIndexRoute: ProtectedSupportIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OnboardingRouteRoute: OnboardingRouteRouteWithChildren,
  SuccessfulLoginRoute: SuccessfulLoginRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SuccessForgotPasswordRoute: SuccessForgotPasswordRoute,
  Verify2faRoute: Verify2faRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  ForgotPasswordVerifyRoute: ForgotPasswordVerifyRoute,
  InviteDeclineRoute: InviteDeclineRoute,
  ForgotPasswordIndexRoute: ForgotPasswordIndexRoute,
  InviteIndexRoute: InviteIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
